### ISSUE TITLE
Compression Performance

### ISSUE THREAD

**Issue by malaverdiere** [EXIficient/exificient#13]
It would be great if we had benchmarks of the different options. I'm especially interested in the performance and size impacts.
Additionally, a performance guide would be useful. This is especially useful for those like me who can't use the CLI interface.

I regularly compress large XML files - about 100-200 Gb worth of data, spread over more than 100 files.
I use Exificient 0.9.6 to do this compression. Because some information is redundant, I need to filter it out, so I'm not using the CLI interface.
I'm not super familiar with XML processing, so there could be very obvious performance red flags below.

This is my core component, simplified as much as I can.

    public static void compressAndSimplify(Path path, Path outPath) throws IOException {
            //Configure the reader
            XMLReader xmlReader = XMLReaderFactory.createXMLReader();
            xmlReader.setFeature("http://xml.org/sax/features/namespaces", true);
            xmlReader.setFeature("http://xml.org/sax/features/validation", false);
            xmlReader.setFeature("http://xml.org/sax/features/namespace-prefixes", false);
            xmlReader.setFeature("http://xml.org/sax/features/resolve-dtd-uris", false);
            xmlReader.setEntityResolver(new NoEntityResolver());

            //Set output parameters
            final EXIFactory exiFactory = DefaultEXIFactory.newInstance();
            exiFactory.setCodingMode(CodingMode.COMPRESSION);
            final FidelityOptions fo = FidelityOptions.createDefault();
            fo.setFidelity(FidelityOptions.FEATURE_LEXICAL_VALUE, true); //keeps the line spacing
            exiFactory.setFidelityOptions(fo);
            EXIResult exiResult = new EXIResult(exiFactory);
            exiResult.setOutputStream(Files.newOutputStream(outPath));

            //This is the component that removes the redundant cases
            final XMLFilter edgeOnlyFilter = new EdgeOnlyFitler(xmlReader);

            //Import output stuff from the exi result object
            edgeOnlyFilter.setContentHandler(exiResult.getHandler());
            edgeOnlyFilter.setProperty("http://xml.org/sax/properties/lexical-handler", exiResult.getLexicalHandler());
            edgeOnlyFilter.setProperty("http://xml.org/sax/properties/declaration-handler", exiResult.getLexicalHandler());
            edgeOnlyFilter.setDTDHandler((DTDHandler) exiResult.getHandler());

            //Do the conversion and compression
            edgeOnlyFilter.parse(new InputSource(Files.newInputStream(path)));
    }

**Comment by danielpeintner** [comment]
Hi @malaverdiere,

Please find below some hints that might be useful.

> `fo.setFidelity(FidelityOptions.FEATURE_LEXICAL_VALUE, true); //keeps the line spacing`

The intent of [Preserve.lexicalValues](https://www.w3.org/TR/exi/#key-preserveLexicalValuesOption) is a different one. Assume one has a float "10" which EXI might turn into "1E1". If you would like to preserve the original form this preserve option should be used.
Preserving new lines et cetera should be re-generated when needed on decoder side given that it increases the size without offering real knowledge.

Another hint I think I would try out is reducing the size (or/and length of string table entries). String tables in EXI tend to grow indefinitely unless you control them. With larger files one keeps adding entries which may make the short identifier longer as expected. Moreover, rather large strings (> 16/24 or so) are usually unlikely strings which appear more often. Hence you may try out

```
exiFactory.setValueMaxLength(16); // or 24 or so
exiFactory.setValuePartitionCapacity(500); // 1000 or any other value that seems to fit
```

These options not necessarily reduce size but should speed up on encoder side.

Another option you might want to set is 

`exiFactory.getEncodingOptions().setOption(EncodingOptions.INCLUDE_OPTIONS);`

This includes all set options in the EXI header (by adding a very little overhead) but provides you a stable way to decode the files in the future without the need to know the used options in the past.

More often also an XML schema helps. In most of the cases this makes a tremendous difference for small files and less difference for larger files.

> Additionally, a performance guide would be useful. This is especially useful for those like me who can't use the CLI interface.

We also offer a [exificient-gui](https://github.com/exificient/exificient-gui) project that should allow you to play around with some option very easily. Is this helpful or are looking for real adives. This is very difficult given that performance differs a lot depending on the actual data.

Hope this helps

**Comment by danielpeintner** [comment]
Close issue (no more guidance to share).

Information can still be retrieved via search
