### ISSUE TITLE
Exificient with Saxon

### ISSUE THREAD

**Issue by ond1** [EXIficient/exificient#19]
Hi,

Is there a way to write to EXI format from Saxon XdmNode.

Reading from an EXI file to a Saxon XdmNode works. Due to Exificient implements the XMLReader interface and that can therefore supply input to Saxon directly as a SAXSource. See as follows:
`
public void testReadingFromEXI_ToXdmNode() {
            EXIFactory exiFactory = DefaultEXIFactory.newInstance();
            try {
                String fileEXI = "xmark4.xml.exi"; // EXI output
                InputSource is = new InputSource(fileEXI);
                SAXSource exiSource = new EXISource(exiFactory);
                exiSource.setInputSource(is);

                Processor proc = new Processor(true);
                XPathCompiler xPathCompiler = proc.newXPathCompiler();
                DocumentBuilder builder = proc.newDocumentBuilder();
                XdmNode node = builder.build(exiSource);            
            } catch (Exception e) {
                e.printStackTrace();
                fail();
            }
        }`

However 

`public void testWritingToEXI_FromXdmNode() {

                EXIFactory exiFactory = DefaultEXIFactory.newInstance();
                try {
                    String fileEXI = "xmark4.xml.exi"; // EXI output
                    String fileXML = "xmark4.xml"; // XML output again
                    OutputStream osEXI = new FileOutputStream(fileEXI);
                    EXIResult exiResult = new EXIResult(exiFactory);
                    exiResult.setOutputStream(osEXI);

                    XMLReader xmlReader = XMLReaderFactory.createXMLReader();
                    xmlReader.setContentHandler(exiResult.getHandler());

                    Processor proc = new Processor(true);
                    XPathCompiler xPathCompiler = proc.newXPathCompiler();

                    DocumentBuilder builder = proc.newDocumentBuilder();

                    XdmNode node = builder.build(new File(fileXML));
                    //Serializer serializer = proc.newSerializer();
                   // serializer.serializeNode(node);                           
                    xmlReader.parse(??????); // The node cannot be cast to InputSource
                    osEXI.close();

                    assertTrue(true);
                } catch (Exception e) {
                    e.printStackTrace();
                    fail();
                }
            }`

Any ideas?

**Comment by danielpeintner** [comment]
I am not fully familiar with Saxon (and XdmNode). Anyhow, looking at the API (see https://www.saxonica.com/html/documentation/javadoc/net/sf/saxon/s9api/XdmNode.html) it seems that `XdmNode.asSource()` reports `javax.xml.transform.Source`.

`XMLInputFactory` can use `javax.xml.transform.Source` to provide an `XMLStreamReader`.

EXIficient in turn (besides SAX, and DOM) also provides support for StAX and one can do

`com.siemens.ct.exi.main.api.stream.StAXEncoder.encode(XMLStreamReader xmlStream);`

after `setOutputStream()` et cetera.

Hope this helps,

-- Daniel

**Comment by ond1** [comment]
Exificient documentation impies that EXIResult.getHandler() returns a SAX ContentHandler that writes EXI to the osEXI outputstream. We can wrap a ContentHandler in a ContentHandlerProxy, which is a Receiver, and therefore a Result, and we should be able to supply that as the transform destination.

Or more simply we can wrap a ContentHandler in a SAXDestination.
See example below:

`             EXIFactory exiFactory = DefaultEXIFactory.newInstance();
                try {
                    String fileEXI = "xmark4-1.xml.exi"; // EXI output
                    String fileXML = "xmark4.xml"; // XML input
                    OutputStream osEXI = new FileOutputStream(fileEXI);
                    EXIResult exiResult = new EXIResult(exiFactory);
                    exiResult.setOutputStream(osEXI);

                    XMLReader xmlReader = XMLReaderFactory.createXMLReader();
                    xmlReader.setContentHandler(exiResult.getHandler());

                    Processor proc = new Processor(false);
                    DocumentBuilder builder = proc.newDocumentBuilder();

                    XdmNode node = builder.build(new File(fileXML));
                    ContentHandler handler = exiResult.getHandler();

                    proc.writeXdmValue(node, new SAXDestination(handler));

                    osEXI.close();`

**Comment by ond1** [comment]
Exificient documentation impies that EXIResult.getHandler() returns a SAX ContentHandler that writes EXI to the osEXI outputstream. We can wrap a ContentHandler in a ContentHandlerProxy, which is a Receiver, and therefore a Result, and we should be able to supply that as the transform destination.

Or more simply we can wrap a ContentHandler in a SAXDestination.
See example below:

`
 EXIFactory exiFactory = DefaultEXIFactory.newInstance();
try {
String fileEXI = "xmark4-1.xml.exi"; // EXI output
String fileXML = "xmark4.xml"; // XML input
OutputStream osEXI = new FileOutputStream(fileEXI);
EXIResult exiResult = new EXIResult(exiFactory);
exiResult.setOutputStream(osEXI);

                XMLReader xmlReader = XMLReaderFactory.createXMLReader();
                xmlReader.setContentHandler(exiResult.getHandler());

                Processor proc = new Processor(false);
                DocumentBuilder builder = proc.newDocumentBuilder();

                XdmNode node = builder.build(new File(fileXML));
                ContentHandler handler = exiResult.getHandler();

                proc.writeXdmValue(node, new SAXDestination(handler));

                osEXI.close();
`

**Comment by ond1** [comment]
EXIFactory exiFactory = DefaultEXIFactory.newInstance();
                try {
                    String fileEXI = "xmark4-1.xml.exi"; // EXI output
                    String fileXML = "xmark4.xml"; // XML input
                    OutputStream osEXI = new FileOutputStream(fileEXI);
                    EXIResult exiResult = new EXIResult(exiFactory);
                    exiResult.setOutputStream(osEXI);

                    XMLReader xmlReader = XMLReaderFactory.createXMLReader();
                    xmlReader.setContentHandler(exiResult.getHandler());

                    Processor proc = new Processor(true);
                    DocumentBuilder builder = proc.newDocumentBuilder();

                    XdmNode node = builder.build(new File(fileXML));
                    ContentHandler handler = exiResult.getHandler();

                    proc.writeXdmValue(node, new SAXDestination(handler));

                    osEXI.close();
`

**Comment by danielpeintner** [comment]
I take your comment as you found a solution that worked. Correct?

**Comment by ond1** [comment]
Hi,

Doing some testing: 

There are probably question marks over how to write comments. It looks like the comments are not coming through. If I am correct the SAX ContentHandler does not provide that capability.

**Comment by danielpeintner** [comment]
EXIficient (in the spirit of the EXI specification) uses a given set of default assumptions if no further information are provided.

You may want to take a look at some options you can set (see https://github.com/EXIficient/exificient/blob/master/README.md#exifactory-settings).

In your case you might want to set the `FidelityOptions` to preserve comments.

**Comment by danielpeintner** [comment]
@ond1  any update? Can we close the issue?

**Comment by ond1** [comment]
hi,

Yes you can close the bug issue.

Thanks
