### ISSUE TITLE
Unable to read one compressed EXI file

### ISSUE THREAD

**Issue by malaverdiere** [EXIficient/exificient#2]
Hello,

I am using exificient to compress some research data. It is a very flat XML structure with no namespaces. Many files decompress without any problem. However, there is one that breaks

I get this exception:

    Caused by: java.lang.IllegalArgumentException
        at java.lang.AbstractStringBuilder.appendCodePoint(AbstractStringBuilder.java:773)
        at java.lang.StringBuilder.appendCodePoint(StringBuilder.java:235)
        at com.siemens.ct.exi.io.channel.AbstractDecoderChannel.decodeStringOnlySupplementaryCodePoints(AbstractDecoderChannel.java:110)
        at com.siemens.ct.exi.io.channel.AbstractDecoderChannel.decodeStringOnly(AbstractDecoderChannel.java:90)
        at com.siemens.ct.exi.core.AbstractEXIBodyDecoder.decodeLocalName(AbstractEXIBodyDecoder.java:172)
        at com.siemens.ct.exi.core.AbstractEXIBodyDecoder.decodeQName(AbstractEXIBodyDecoder.java:135)
        at com.siemens.ct.exi.core.AbstractEXIBodyDecoder.decodeStartElementGenericStructure(AbstractEXIBodyDecoder.java:480)
        at com.siemens.ct.exi.core.EXIBodyDecoderInOrder.decodeStartElement(EXIBodyDecoderInOrder.java:126)
        at com.siemens.ct.exi.api.stream.StAXDecoder.decodeEvent(StAXDecoder.java:279)
        at com.siemens.ct.exi.api.stream.StAXDecoder.next(StAXDecoder.java:210)

My code:

       final EXIFactory exiFactory = DefaultEXIFactory.newInstance();
       final XMLStreamReader streamReader = new StAXDecoder(exiFactory);
       instance.setInputStream(Files.newInputStream(fileToRead));
       while(streamReader.hasNext()){
            streamReader.next();
            switch(streamReader.getEventType()){
       //...
      }

*Other details*
Platform: Fedora Linux 23
Java: OpenJDK 1.8.0_92
Exificient: 0.9.6

**Comment by danielpeintner** [comment]
Hi,

Looking at the stacktrace it seem the XML instance contains non-ASCII element names (which per se shouldn't be an issue).

Do you mind sharing your XML instance so that we can look into the issue?

**Comment by malaverdiere** [comment]
This is very odd because all the data I've seen so far is US-ASCII.

As for sharing, the problem is that the files are veeeery big - 800+ mb.
By implication, creating a minimal working example is not trivial.

What do you suggest?

**Comment by danielpeintner** [comment]
Mhh, without actually reconstructing the issue it is very difficult to track down the problem.

Looking at Java's AbstractStringBuilder class there seems to be only one reason which fires IllegalArgumentException. If the passed codePoint is invalid..

e.g., try the following code

```
		StringBuilder sb = new StringBuilder();
		sb.appendCodePoint(0); // works just fine
		
		int codePoint = -1;
		System.out.println(Character.isBmpCodePoint(codePoint));  // false
		System.out.println(Character.isValidCodePoint(codePoint)); // false
		
		sb.appendCodePoint(codePoint); // will cause IllegalArgumentException for -1 et cetera
```

Something similar might happen in your case.

I wonder whether you can track/log your data to identify the issue .... or maybe reducing Javas heap size so that the issue pops up with smaller files also.

That said, I am not sure whether the issue relates to the size.. to me it looks like the stream is corrupted or so because the EXI call goes through decodeStringOnlySupplementaryCodePoints(..) which indicates that the string is non ASCII and you say it is supposed to be US-ASCII.

**Comment by malaverdiere** [comment]
Trying to troubleshoot, I did this:

     file -bi file.xml
     application/xml; charset=us-ascii

So we're supposed to have ASCII. And when I look at it on the console, I have ascii as well. However, the whole file on a single line.

I read through the XML files for which the EXI reader threw an exception and looked for invalid characters, to no avail. I looked for instances not contained in this list of characters:

`?=:/-.0123456789aAbBcCdDeEfFgGhHiUjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ<>,'"\n\t`

I'll give your snippet a shot shortly.

**Comment by malaverdiere** [comment]
As for your snippet, this is what I'm getting:

    false
    false
    Exception in thread "main" java.lang.IllegalArgumentException

**Comment by danielpeintner** [comment]
The code results are as expected.

Do you have any chance to share the file with me. Without seems to be difficult to track the issue (there are also free online services such as wetransfer or fileconvoy).

OR

you try to log what happens in your StAX loop..

**Comment by malaverdiere** [comment]
This is the smallest one: 
https://drive.google.com/file/d/0B4eQtxyr2YejZjJNbXdReE5qODQ/view?usp=sharing

By the way, I've tested by re-encoding a bunch and all of them in that batch are breaking. I encoded using `exificient -encode -compression -i file.xml`

**Comment by malaverdiere** [comment]
Problem found: I had encoded my files using the -compression flag. However, my reader didn't have the call to exiFactory.setCodingMode(CodingMode.COMPRESSION) - I had expected this to be auto-detected.

Adding this call, I am not getting any exceptions and my unit tests are working.

**Comment by danielpeintner** [comment]
The "auto-detect" just works if the EXI options document is included in the header of the EXI stream which by default is not the case.

This can be done with "-includeOptions" on the shell

OR

setting the EncodingOptions for the EXIFactory to do so.

Hope this helps,

-- Daniel
