### ISSUE TITLE
Decoding a 82 MB file taking too long

### ISSUE THREAD

**Issue by ond1** [EXIficient/exificient#20]
Hi,

I successfully managed to encode the following XML file (in 2 seconds): treebank_e.xml from 
http://aiweb.cs.washington.edu/research/projects/xmltk/xmldata/www/repository.html#treebank
http://aiweb.cs.washington.edu/research/projects/xmltk/xmldata/data/treebank/treebank_e.xml

However the decoding of the file from EXI to XML is taking a considerable amount of time (Still running after an hour). Are there any limits to EXificient? Or any ideas as to what is going wrong.

See simple code below:

 EXIFactory exiFactory = DefaultEXIFactory.newInstance();
        try {
            String fileEXI = "treebank_e.xml.exi"; // EXI output
            String fileXML = "treebank_e.xml.exi.xml"; // XML output again
            Result result = new StreamResult(fileXML);
            InputSource is = new InputSource(fileEXI);
            SAXSource exiSource = new EXISource(exiFactory);
            exiSource.setInputSource(is);
            TransformerFactory tf = TransformerFactory.newInstance();
            Transformer transformer = tf.newTransformer();
            long start = new Date().getTime();
            transformer.transform(exiSource, result);
            long end = new Date().getTime();
            System.err.println("Av Time: " + (end - start) / 10 + "ms");
            assertTrue("Av Time: " + (end - start) / 10 + "ms", true);
        } catch (Exception e) {
                    e.printStackTrace();
                    fail();
                }

**Comment by danielpeintner** [comment]
I tried to reproduce your issue and I cannot find any issue (see https://github.com/EXIficient/exificient/blob/master/src/test/java/com/siemens/ct/exi/main/data/IssueTestCase.java#L53-L90).

If I run this test on my old windows box encoding takes much longer than decoding.

```
Encode time for ./data/issues/issue20/treebank_e.xml is 8430ms
Decode time for ./data/issues/issue20/treebank_e.xml is 3733ms
```

**Comment by ond1** [comment]
Seems strange. What version of Java are you running with? I am running with Java 1.8.

**Comment by danielpeintner** [comment]
I am on Java 8 also on Windows.

I did notice that Travis build failed on decoding this file (see https://api.travis-ci.org/v3/job/416725053/log.txt).

Maybe there is a glitch somewhere but maybe it is also because of the size of the file.
Will look into it...

**Comment by danielpeintner** [comment]
It seems that the issue relates to memory consumption. Please try to set the following which considers strings to be added to the string table only if the are at most of length 16.

`exiFactory.setValueMaxLength(16);`

In your case it seems that the consumed memory (heap) goes close to maximum and decoding time is mostly spend on garbage collection.

**Comment by ond1** [comment]
Thanks it works fine now.

**Comment by danielpeintner** [comment]
Thanks!
