### ISSUE TITLE
Loading schemas with import keyword in Android

### ISSUE THREAD

**Issue by gogos-venge** [EXIficient/exificient#24]
I know there is a closed issue for the android, also concerning grammars, I already read through it but I think the problem I'm facing isn't described there. What I'm trying to do is create the grammars for https://github.com/dumistoklus/svg-xsd-schema svg schema but I get this error:
```
[xs-warning] schema_reference.4: Failed to read schema document 'xlink.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>
[xs-warning] schema_reference.4: Failed to read schema document 'namespace.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>
```
I think I found which library (probably xerces, edit: and more specifically in the method `protected XSDocumentInfo constructTrees(Element schemaRoot, String locationHint, XSDDescription desc, boolean nsCollision)` in class `XSDHandler`, of `package org.apache.xerces.impl.xs.traversers;`) fails to resolve the **imports**. Failing to resolve the imports is natural though, since I get the InputStream from the assets folder, and those files are not accessible by the filesystem directly:

```java
//c is android context
EXIFactory exiFactory = DefaultEXIFactory.newInstance();
exiFactory.setCodingMode(CodingMode.COMPRESSION);     
exiFactory.setGrammars(GrammarFactory.newInstance().createGrammars(c.getAssets().open("svg.xsd")));
```

Although I can't skip providing a schema for the svg since:
1) Using xsd I got a 25% smaller result, and size is really crucial for me. 
2) The svg must be valid.

I cannot flatten the xsd. It's not possible.
Also I both used `XSDGrammarsBuilder xsd = XSDGrammarsBuilder.newInstance();` and `XMLSchemaLoader schemaLoader = new XMLSchemaLoader();` just to get similar errors.

Is this a bug or is there a way to provide the rest of the xsds for the Grammar Factory (pool, cache)?

**Comment by danielpeintner** [comment]
Hi,

EXIficient uses Xerces-J to load XML schemas. IF, for whatever reason, Xerces-J fails to retrieve loading files EXI processing fails.

To allow *overriding* where a certain file can be found one needs to specify an `XMLEntityResolver` in 
`createGrammars(...)` (see [here](https://github.com/EXIficient/exificient-grammars/blob/master/src/main/java/com/siemens/ct/exi/grammars/GrammarFactory.java#L84-L95)).

An example can be found here
https://github.com/EXIficient/exificient/blob/master/src/test/java/com/siemens/ct/exi/main/data/TestXSDResolver.java

In use-cases where you want to avoid loading schemas and creating EXI grammars over an over again on *limited* devices you may want to look into the following explorative work.
https://github.com/EXIficient/exificient-grammars/#exchange-of-exi-grammars

Hope this helps.

-- Daniel

**Comment by gogos-venge** [comment]
Magnificent...
```java
public class XSDResolver implements XMLEntityResolver {

    Context context;

    public XSDResolver(Context context){
        this.context = context;
    }

    @Override
    public XMLInputSource resolveEntity(XMLResourceIdentifier resourceIdentifier) throws XNIException, IOException {
        String literalSystemId = resourceIdentifier.getLiteralSystemId();

        if("xlink.xsd".equals(literalSystemId)){
            InputStream is = context.getAssets().open("xlink.xsd");
            return new XMLInputSource(null, null, null, is, null);
        } else if("namespace.xsd".equals(literalSystemId)){
            InputStream is = context.getAssets().open("namespace.xsd");
            return new XMLInputSource(null, null, null, is, null);
        } else if("svg.xsd".equals(literalSystemId)){
            InputStream is = context.getAssets().open("svg.xsd");
            return new XMLInputSource(null, null, null, is, null);
        }
        return null;
    }
}
```
And upon writing the above code, calling this line `exiFactory.setGrammars(GrammarFactory.newInstance().createGrammars("svg.xsd", new XSDResolver(c)));`, actually created all the grammars correctly.
Sorry that this was a support request and not an actual issue.

You've been of great help.
