### ISSUE TITLE
OutOfMemoryError while using Compression

### ISSUE THREAD

**Issue by buko** [EXIficient/exificient#26]
We're encoding lots (~150,000) small XML files using the CodingMode.Compression. To speed up the encoding 72 threads (processorCount * 3) are used. Each XML file is small (about 150 bytes, just one element and 4-5 sub-elements). We can relatively consistently produce OutOfMemory Errors:

```
Exception in thread "pool-1-thread-37" java.lang.OutOfMemoryError
	at java.base/java.util.zip.Deflater.init(Native Method)
	at java.base/java.util.zip.Deflater.<init>(Deflater.java:201)
	at com.siemens.ct.exi.core.coder.EXIBodyEncoderReordered.getStream(EXIBodyEncoderReordered.java:158)
	at com.siemens.ct.exi.core.coder.EXIBodyEncoderReordered.setOutputStream(EXIBodyEncoderReordered.java:113)
	at com.siemens.ct.exi.core.coder.EXIStreamEncoderImpl.encodeHeader(EXIStreamEncoderImpl.java:68)
	at com.siemens.ct.exi.main.api.stream.StAXEncoder.setOutputStream(StAXEncoder.java:109)
```

This happens on the call to StaxEncoder.setOutputStream. We create a new StaxEncoder every time we write a file and then we are careful to also close the StaxEncoder:

```java
final StAXEncoder writer = new StAXEncoder(exi);
		try { 
			writer.setOutputStream(out);
			writer.writeStartDocument("1.0");
			write(city, writer);
			writer.writeEndDocument();
		} finally {
			writer.close();
		}
```

I believe the probelm is very similar to other issues: [Deflate.end() is never called leading to excessive memory use and even OutOfMememoryErrors](https://github.com/jwtk/jjwt/issues/392).

In the EXIBodyEncoderReordered at line 158 a new Deflater is created and passed to DeflaterOutputStream:

```java
protected OutputStream getStream() {
		if (codingMode == CodingMode.COMPRESSION) {
			// reuse deflater
			if (deflater == null) {
				Object o = this.exiFactory.getEncodingOptions().getOptionValue(
						EncodingOptions.DEFLATE_COMPRESSION_VALUE);
				int cl = Deflater.DEFAULT_COMPRESSION;
				if (o != null && o instanceof Integer) {
					cl = (Integer) o;
				}
				deflater = new Deflater(cl, true);
			} else {
				deflater.reset();
			}
			deflaterOS = new DeflaterOutputStream(os, deflater);
			return deflaterOS;
		} else {
			assert (codingMode == CodingMode.PRE_COMPRESSION);
			return os;
		}
	}
```

The DeflaterOutputStream#close() method does NOT call Deflater#end()  if a Deflater was passed to its constructor. It only calls Deflater#end() if it created the Deflater:

```java
public void close() throws IOException {
        if (!closed) {
            finish();
            if (usesDefaultDeflater)
                def.end();
            out.close();
            closed = true;
        }
    }
```

The result is that every time you create a StaxEncoder with Compression a Deflater object is created and never end()'d. After about ~120-150K StaxEncoder objects are created an OOME is generated.

The solution seems to be that if StaxEncoder (or specifically the EXIBodyEncoderReordered class) is going to create a Deflater then it should call Deflater.end() when the StaxEncoder is close()'d.

**Comment by danielpeintner** [comment]
I tried your example with lower memory and yes, I do see 

`Exception in thread "pool-1-thread-3" java.lang.OutOfMemoryError: GC overhead limit exceeded`

Having said that, I don't believe it has to do with Deflate. I tried without by removing the following option.
`factory.setCodingMode(CodingMode.COMPRESSION);`
and I do see the same issue.

This means that there is another issue, most likely with treading.

I also tried to switch off string tables.
`factory.setValueMaxLength(0);`

This did not help either.

**Comment by danielpeintner** [comment]
I updated the snapshot version on Sonatype, `1.0.5-SNAPSHOT`

https://oss.sonatype.org/content/repositories/snapshots/com/siemens/ct/exi/exificient-core/1.0.5-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/com/siemens/ct/exi/exificient/1.0.5-SNAPSHOT/

The change is minimal, I added `deflater.end()` in final `flush()`.

see https://github.com/EXIficient/exificient-core/commit/2033f888605099c717cb8739b3bc3ebf5d897f11

Please let me know whether this helps.

**Comment by buko** [comment]
Will you do another exificient release with this bug fix?

**Comment by danielpeintner** [comment]
Let's first resolve https://github.com/EXIficient/exificient/issues/28

**Comment by danielpeintner** [comment]
https://github.com/EXIficient/exificient/issues/28 closed.
