### ISSUE TITLE
StaxDecoder does not follow the contract for XMLStreamReader#getElementText

### ISSUE THREAD

**Issue by buko** [EXIficient/exificient#28]
[XMLStreamReader#getElementText() is supposed to be called at the START_ELEMENT event.](https://docs.oracle.com/javase/8/docs/api/javax/xml/stream/XMLStreamReader.html#getElementText--) From then, given the proposed implementation, it's supposed to advance to the end of the element collecting text or white space until it hits an END_ELEMENT.

The [StAXDecoder#getElementText method](https://github.com/EXIficient/exificient/blob/650ac0ec481d5e5ca2f0488eba099834c1ab2032/src/main/java/com/siemens/ct/exi/main/api/stream/StAXDecoder.java#L408) does something very different... which breaks all applications that previously read XML but are now reading EXI.

(BTW I wonder if there's some kind of standards compliant TCK for these APIs that EXI could be tested against?)

**Comment by danielpeintner** [comment]
Can you elaborate "what" issue is caused or to put differently.

May I ask you to propose a test (e.g., in [StAXCoderTestCase.java](https://github.com/EXIficient/exificient/blob/650ac0ec481d5e5ca2f0488eba099834c1ab2032/src/test/java/com/siemens/ct/exi/main/api/stream/StAXCoderTestCase.java) that shows the issue (or the expected result).



> (BTW I wonder if there's some kind of standards compliant TCK for these APIs that EXI could be tested against?)

SAX has been extensively tested in various environments.  StAX is probably not tested in the same manner.

Note: there is [TestSAXEncoder.java](https://github.com/EXIficient/exificient/blob/650ac0ec481d5e5ca2f0488eba099834c1ab2032/src/test/java/com/siemens/ct/exi/main/TestSAXEncoder.java) and  [TestStAXDecoder.java](https://github.com/EXIficient/exificient/blob/650ac0ec481d5e5ca2f0488eba099834c1ab2032/src/test/java/com/siemens/ct/exi/main/TestStAXDecoder.java) that didn't show issues when being used.
Do you have a specific setup?

**Comment by buko** [comment]
This is the code for the standard XMLStreamReader:

```java
 /**
     * Reads the content of a text-only element. Precondition: the current event
     * is START_ELEMENT. Postcondition: The current event is the corresponding
     * END_ELEMENT.
     *
     * @throws XMLStreamException if the current event is not a START_ELEMENT or
     * if a non text element is encountered
     */
    public String getElementText() throws XMLStreamException {

        if (getEventType() != XMLStreamConstants.START_ELEMENT) {
            throw new XMLStreamException(
                    "parser must be on START_ELEMENT to read next text", getLocation());
        }
        int eventType = next();
        StringBuilder content = new StringBuilder();
        while (eventType != XMLStreamConstants.END_ELEMENT) {
            if (eventType == XMLStreamConstants.CHARACTERS
                    || eventType == XMLStreamConstants.CDATA
                    || eventType == XMLStreamConstants.SPACE
                    || eventType == XMLStreamConstants.ENTITY_REFERENCE) {
                content.append(getText());
            } else if (eventType == XMLStreamConstants.PROCESSING_INSTRUCTION
                    || eventType == XMLStreamConstants.COMMENT) {
                // skipping
            } else if (eventType == XMLStreamConstants.END_DOCUMENT) {
                throw new XMLStreamException(
                        "unexpected end of document when reading element text content");
            } else if (eventType == XMLStreamConstants.START_ELEMENT) {
                throw new XMLStreamException("elementGetText() function expects text "
                        + "only elment but START_ELEMENT was encountered.", getLocation());
            } else {
                throw new XMLStreamException(
                        "Unexpected event type " + eventType, getLocation());
            }
            eventType = next();
        }
        return content.toString();
    }
```

This is StaxDecoder:

```java
	public String getElementText() throws XMLStreamException {
		// Reads the content of a text-only element,
		// an exception is thrown if this is not a text-only element.
		switch (getEventType()) {
		case XMLStreamConstants.CHARACTERS:
		case XMLStreamConstants.SPACE:
			return characters.toString();
		default:
			throw new RuntimeException("Unexpected event, id=" + getEventType());
		}
	}
```

The StaxDecoder behaves completely differently from the standard and does not conform to the javadoc at all. There's an easy fix here... just copy the standard code. After all the implementation is all but mandated by the Javadoc.

**Comment by danielpeintner** [comment]
No response -> assume it is fine as is now.
