### ISSUE TITLE
Cdata section is removed

### ISSUE THREAD

**Issue by bhaskarrana** [EXIficient/exificient#29]
Hi Team,
I did the encode xml first and then decode it back.
Found that CDATA is removed  
<script>var test = Class.create();  
orignal
 <script><![CDATA[var test = Class.create();  
and it start replace && as  &amp;&amp;
Is there an option to ignore the cdata section.
Kindly advice.
Regards
Bhaskar Rana

**Comment by danielpeintner** [comment]
The EXI specification has so called [Fidelity Options](https://www.w3.org/TR/exi/#fidelityOptions). These preserve options can specify what is to be preserved. The default options are set to achieve the best compression.
e.g., in _many_ use-cases comments are not needed etc.

EXIficient allows one to specify these options, look for "com.siemens.ct.exi.core.FidelityOptions" in https://github.com/EXIficient/exificient#exifactory-settings.
You may want to use "FEATURE_DTD".

Note: This options on encoder and decoder side need to be the same.

**Comment by danielpeintner** [comment]
No further response -> closing
