### ISSUE TITLE
NullPointerExceptoin when trying to parse EXI file

### ISSUE THREAD

**Issue by rhoehener** [EXIficient/exificient#30]
Using exificient 1.0.4

I'm trying to read an EXI stream (see test.zip) that I extracted from PDF417 barcode data generated by eFisc2021 (https://steuerverwaltung.tg.ch/hilfsmittel/efisc-steuererklaerungssoftware.html/2958)

I don't know if I extracted the correct byte range. The cookie and header with options (compression) seem to be correct, but the last step of `EXIStreamDecoderImpl.decodeHeader` fails with NPE:

```
Exception in thread "main" com.siemens.ct.exi.core.exceptions.EXIException: java.lang.NullPointerException
	at com.siemens.ct.exi.main.api.dom.DOMBuilder.parse(DOMBuilder.java:120)
	at com.siemens.ct.exi.main.api.dom.DOMBuilder.parse(DOMBuilder.java:91)
	at ExiTest.main(ExiTest.java:13)
Caused by: java.lang.NullPointerException
	at com.siemens.ct.exi.core.coder.AbstractEXIBodyCoder$RuntimeUriContext.getQNameContext(AbstractEXIBodyCoder.java:487)
	at com.siemens.ct.exi.core.coder.AbstractEXIBodyDecoder.decodeLocalName(AbstractEXIBodyDecoder.java:184)
	at com.siemens.ct.exi.core.coder.AbstractEXIBodyDecoder.decodeQName(AbstractEXIBodyDecoder.java:133)
	at com.siemens.ct.exi.core.coder.AbstractEXIBodyDecoder.decodeStartElementGenericStructure(AbstractEXIBodyDecoder.java:484)
	at com.siemens.ct.exi.core.coder.EXIBodyDecoderReordered.preReadBlockStructure(EXIBodyDecoderReordered.java:401)
	at com.siemens.ct.exi.core.coder.EXIBodyDecoderReordered.initForEachRun(EXIBodyDecoderReordered.java:194)
	at com.siemens.ct.exi.core.coder.EXIBodyDecoderReordered.setInputStream(EXIBodyDecoderReordered.java:240)
	at com.siemens.ct.exi.core.coder.EXIStreamDecoderImpl.decodeHeader(EXIStreamDecoderImpl.java:97)
	at com.siemens.ct.exi.main.api.sax.SAXDecoder.parse(SAXDecoder.java:246)
	at com.siemens.ct.exi.main.api.dom.DOMBuilder.parse(DOMBuilder.java:115)
	... 2 more
```

Test file: [test.zip](https://github.com/EXIficient/exificient/files/9937617/test.zip)

Test code:

```
import java.io.File;
import java.io.FileInputStream;
import com.siemens.ct.exi.core.helpers.DefaultEXIFactory;
import com.siemens.ct.exi.main.api.dom.DOMBuilder;

public class ExiTest {
  public static void main(String[] args) throws Exception {
    new DOMBuilder(DefaultEXIFactory.newInstance()).parse(new FileInputStream(new File("test.exi")));
  }
}
```

**Comment by danielpeintner** [comment]
> I don't know if I extracted the correct byte range. The cookie and header with options (compression) seem to be correct, but the last step of `EXIStreamDecoderImpl.decodeHeader` fails with NPE:

Most likely the byte range was not correct...  even though the EXI cookie "$EXI" in the beginning is correct.
Looking at the text.exi you provided it seems strange to me that it contains _new-lines_ and _spaces_ like right after the cookie...

BTW, NPE should not happen anyway :-(

**Comment by rhoehener** [comment]
Thank you very much for looking into it!

The complete test data is coming from this barcode, which I scanned with a barcode reader/pistol. The bytes arriving at the serial port are: [PDF417-Bytes.zip](https://github.com/EXIficient/exificient/files/9960452/PDF417-Bytes.zip)

I didn't notice the new-lines because i only looked at the data with HxD to cut all bytes before the $EXI cookie.

![screenshot](https://user-images.githubusercontent.com/13407181/200548380-c9a895c8-5bad-433c-99f5-1261f2df2002.png)

**Comment by rhoehener** [comment]
I see the LF (0x0A) bytes, but I don't see any spaces (0x20).

**Comment by danielpeintner** [comment]
> I see the LF (0x0A) bytes, but I don't see any spaces (0x20).

Right after $EXI there is A0, ..it's an "NO-BREAK SPACE"... not sure if this belongs to the EXI stream or not.

Anyhow, removing the new lines does not help.. results in "not valid unicode codepoint".
I think this becomes _guessing_ what is wrong with the stream rather than knowing what is going on...

**Comment by rhoehener** [comment]
> Right after $EXI there is A0, ..it's an "NO-BREAK SPACE"... not sure if this belongs to the EXI stream or not.

Indeed.

> I think this becomes _guessing_

Yes it is. I didn't even know about EXI before googling that $EXI mark right after the header.

Anyway, thank you for your time!

**Comment by danielpeintner** [comment]
BTW, the file also contains the following statement `Axsd=2021DeklarationTGnat_V4.xsd`
IF the EXI stream is encoded by the means of this XSD you also need this information to be able to properly decode it...

**Comment by rhoehener** [comment]
Ah ok, I didn't know the schema was required for decoding. Or what does 'properly' mean here?

**Comment by rhoehener** [comment]
I tried this just now but no luck:
```
    EXIFactory factory = DefaultEXIFactory.newInstance();
    factory.getDecodingOptions().setOption(DecodingOptions.IGNORE_SCHEMA_ID);
    new DOMBuilder(factory).parse(new FileInputStream(new File("test.bin")));
```

**Comment by danielpeintner** [comment]
> Ah ok, I didn't know the schema was required for decoding. Or what does 'properly' mean here?

EXI is a [W3C specification](https://www.w3.org/TR/exi/) with several options. For example EXI can use XML schema information to even further improve compression and performance. However, this means that both ends need to agree on the *same* schema information.

There are many more options and I guess you would need to understand better the EXI format (e.g., see [EXI Primer](https://www.w3.org/TR/exi-primer/)) as well as *how* it is used in your context.

Having said that, I don't think this is an issue of the EXIficient library and I think we can close the issue itself.

**Comment by rhoehener** [comment]
I've been reading the spec for a while now, and I see you are an editor.

So, just to confirm: If the stream was encoded with schema information, there is no way to even partially decode it without access to the schema? For example with dummy element names?

And yes, feel free to close.

**Comment by danielpeintner** [comment]
> So, just to confirm: If the stream was encoded with schema information, there is no way to even partially decode it without access to the schema? For example with dummy element names?

FYI: IF a schema was used for encoding the EXI stream the schema needs to be *known* also on the receiver side.

**Comment by rhoehener** [comment]
Thanks. Schema then apparently acts like a kind of inbuilt encryption key.

Trying to write a basic decoder and already stuck on the options stream: Is there a table of the event codes of the options document somewhere?

**Comment by rhoehener** [comment]
> Right after $EXI there is A0, ..it's an "NO-BREAK SPACE"... not sure if this belongs to the EXI stream or not.

A0 = 1010 0000: dermining bit '10', options bit '1', version '0 0000' (= final version 1)

**Comment by danielpeintner** [comment]
I am sorry. I don't have the bandwidth to answer more questions...

**Comment by rhoehener** [comment]
👍
