### ISSUE TITLE
Console error ouput

### ISSUE THREAD

**Issue by BBE78** [EXIficient/exificient#36]
Some piece of code is using  `System.err.println()` to trace error messages.
This is not recommended, and the use of a logger framework is better

**Comment by danielpeintner** [comment]
@BBE78 I totally agree with your statements and your recommendation.

Having said that, I don't think I will have time to implement that.
If you plan to work on a PR that is highly accepted and I will try to find time reviewing it..

**Comment by BBE78** [comment]
Hi @danielpeintner, That's the plan, coming soon...

**Comment by BBE78** [comment]
Hi @danielpeintner , 3 PR https://github.com/EXIficient/exificient-core/pull/11, https://github.com/EXIficient/exificient-grammars/pull/22, https://github.com/EXIficient/exificient/pull/37 are available to fix this issue
Happy review!

**Comment by danielpeintner** [comment]
Thanks for your work and your contribution!

I added some minor comments to all the PRs ..

**Comment by BBE78** [comment]
Hi, I will take them into account in next days...

**Comment by danielpeintner** [comment]
Hi @BBE78 

Thanks for your work. All your PRs should be merged by now 👍

**Comment by danielpeintner** [comment]
Issue can be closed, right?

**Comment by BBE78** [comment]
> Issue can be closed, right?

I think so
