### ISSUE TITLE
exificient cli

### ISSUE THREAD

**Issue by dfdias** [EXIficient/exificient#40]
Hello

I have built exificient using maven clean install

When I try to run the cli utility it throws the following error :
java -classpath target/exificient.jar com.siemens.ct.exi.main.cmd.EXIficientCMD  -decode -i  abc.exi -o abc.exi.xml

Error:
Exception in thread "main" java.lang.NoClassDefFoundError: com/siemens/ct/exi/core/helpers/DefaultEXIFactory
        at com.siemens.ct.exi.main.cmd.EXIficientCMD.parseArguments(EXIficientCMD.java:233)

Any hints on what I am missing ?

Thanks in advance 

DD

**Comment by danielpeintner** [comment]
EXIficient has dependencies like 
* exificient-core
* exificient-grammars
* ...

see
https://github.com/EXIficient/exificient/blob/9e2c90d251d3f2b8602ed8637021b28246e07c6d/pom.xml#L46-L66

Note: On http://exificient.github.io/java/ there is a pre-built runnable Jar with UI, see [here](http://exificient.github.io/java/exificient-gui-jar-with-dependencies.jar)

**Comment by dfdias** [comment]
I thought maven would get those...sorry for the question
I guess if I run jar tf  exificient-gui jar the cmd class will be there.
Can you give a detailed description on how to build with the dependencies?

Thanks in advance :=)

**Comment by danielpeintner** [comment]
This is not really an EXIficient question.. anyhow..

You might want to add the following snippet to the `pom.xml` in the plugin `maven-assembly-plugin`

```
            <executions>
                <execution>
                    <id>assemble-all</id>
                    <phase>package</phase>
                    <goals>
                        <goal>single</goal>
                    </goals>
                </execution>
            </executions>
```

afterwards running `mvn clean -DskipTests=true package` creates a file `exificient-jar-with-dependencies.jar` also.

see https://stackoverflow.com/questions/16222748/building-a-fat-jar-using-maven

Note: I updated the pom.xml also in https://github.com/EXIficient/exificient/commit/6c16b067fd86839a40e2eae4ae7a95d7ec538f93

**Comment by dfdias** [comment]
Ok :)

Thank you very much, and sorry for the trouble :) :+1:
