### ISSUE TITLE
Request to implement C# version

### ISSUE THREAD

**Issue by snikeguo** [EXIficient/exificient#41]
RT.

**Comment by danielpeintner** [comment]
We will not have the time to work on a C# implementation.

Some thoughts:
* I think there are (at least commercial) .NET implementations, see https://www.w3.org/XML/EXI/#implementations 
* I also believe I have heard that there is a .NET runtime which is capable of running Java code (or at least bridging)

**Comment by danielpeintner** [comment]
FYI: I think I found the project I had in mind, see https://github.com/ikvmnet/ikvm
