### ISSUE TITLE
Encode/decode with "Compatible XSDs"

### ISSUE THREAD

**Issue by lbeuster** [EXIficient/exificient#7]
Hi,

I played a little bit with different (but "compatible") XSD on ecoder and decoder side and found out the following problems:

(1) Added an additional optional element to an existing type
- I encoded and decoded an xml snippet without the new element. 
- If the encoder uses the new xsd and the decoder the old xsd everything seems to work fine.
- If the encoder uses the old xsd and the decoder the new xsd I get an an EOFException
- without exi both cases work fine, with exi only one case works

(2) Added an additional type
- I encoded and decoded an xml snippet without using the new type.
- If the encoder uses the new xsd and the decoder the old xsd I get wrong data after decoding.
- If the encoder uses the old xsd and the decoder the old xsd I get an EOFException.
- without exi both cases work, with exi none of them

Both issue are problems for us, because both sides are encoder and decoder and we use the same xsd - and we cannot change that.
Is the problem on exi side or on mine? ;)

Best regards
Lars

**Comment by danielpeintner** [comment]
Hi Lars,

The EXI specification requires to use the "same" schema information on both side IF schema-informed streams are to be used.

Changing the XSDs in general produces not the same schema information. There are corner cases that may still work but this is out of scope for the EXI specification and EXIficient as one implementation.

There are different possibilities to resolve such issues. 

1) not use schema information at all
This is probably the most stable solution given that there are no dependencies at all. That said, this might still give good performance but not the same as in schema-informed mode

2) Use the "same" schema knowledge on both side 
It does not matter if a schema is not valid. EXI and EXIficient in non-strict mode can deal with deviant data. One just needs to ensure that both schemas are the same.

3) use of schemaId
One needs to use schemaId (https://www.w3.org/TR/exi/#key-schemaIdOption) in each EXI stream to indicate which schema was used for a given encoding. The recipient needs to have access to this schema..
The overhead can be minimal ... "A" --> indicating schema 1, .. "B" --> indicating schema 2 et cetera

4) Some kind of handshake on top of EXI
One can build some handshake protocol on top of EXI to ensure the right use of schemas... what is supported by both, encoder and decoder..

There might be other alternatives...

I just want to give you an idea.

Hope this helps,

-- Daniel

**Comment by lbeuster** [comment]
Hi Daniel,
thanks for the answer. I think (2) and (3) are both very good solutions for us.

Best regards
Lars
