### ISSUE TITLE
Autodetect coding mode during decoding

### ISSUE THREAD

**Issue by lbeuster** [EXIficient/exificient#8]
I would be nice if the decoder could auto detect the coding mode of the encoded exi.
I don't know if this is possible according to the exi spec, but it would make exi coding/decoding less fragile.

Thanks
Lars

**Comment by danielpeintner** [comment]
Hi Lars,

The decoder can "autodetect" the used options and coding modes IF the EXI stream contains this information.

In well-defined use-cases informing the recipient every time about the same used options is not desired and creates an overhead. In other cases when it is possible to use different options I would require the EXI options document in the EXI header (see https://www.w3.org/TR/exi/#key-options).

In EXIficient one can trigger to include the options by setting.
```
EXIFactory.setEncodingOptions(...)
EncodingOptions --> INCLUDE_OPTIONS
```

There is another option for schemaIds..
`EncodingOptions --> INCLUDE_SCHEMA_ID`

Hope this helps,

-- Daniel

**Comment by lbeuster** [comment]
Hi Daniel,
thanks for pointing me to the EcodingOptions - this will help ;)

Best regards
Lars
