### ISSUE TITLE
Problem with marshall object with JAXB and StAXEncoder

### ISSUE THREAD

**Issue by mkrzempek** [EXIficient/exificient#9]
I try to marshall Java object using JAXB API. Using EXIResult object works all right.

But when I try to do it through StaXEncoder class within method like this:
```
    public void marshalToExiStream(CmmMessage jaxbMessage, OutputStream outputStream) throws EXIException, IOException, JAXBException {
        StAXEncoder encoder = new StAXEncoder(exiFactory);
        encoder.setOutputStream(outputStream);

        produceMarshaller().marshal(jaxbMessage, encoder);
    }
```

I receive such error because deflate stream is finished:

> Caused by: java.io.IOException: write beyond end of stream
> 	at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:201)
> 	at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:188)
> 	at com.siemens.ct.exi.io.channel.ByteEncoderChannel.encode(ByteEncoderChannel.java:70)
> 	at com.siemens.ct.exi.io.channel.AbstractEncoderChannel.encodeUnsignedInteger(AbstractEncoderChannel.java:151)
> 	at com.siemens.ct.exi.datatype.strings.StringEncoderImpl.writeValue(StringEncoderImpl.java:71)
> 	at com.siemens.ct.exi.datatype.StringDatatype.writeValue(StringDatatype.java:81)
> 	at com.siemens.ct.exi.types.TypedTypeEncoder.writeValue(TypedTypeEncoder.java:70)
> 	at com.siemens.ct.exi.core.EXIBodyEncoderReordered.closeBlock(EXIBodyEncoderReordered.java:197)
> 	at com.siemens.ct.exi.core.EXIBodyEncoderReordered.flush(EXIBodyEncoderReordered.java:278)
> 	at com.siemens.ct.exi.api.stream.StAXEncoder.flush(StAXEncoder.java:549)
> 	at com.sun.xml.internal.bind.v2.runtime.output.XMLStreamWriterOutput.endDocument(XMLStreamWriterOutput.java:97)
> 	at com.sun.xml.internal.bind.v2.runtime.output.ForkXmlOutput.endDocument(ForkXmlOutput.java:59)
> 	at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.endDocument(XMLSerializer.java:836)
> 	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.postwrite(MarshallerImpl.java:362)
> 	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:309)
> 	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:163)
>

**Comment by danielpeintner** [comment]
https://github.com/EXIficient/exificient/commit/b886b419dd99bea1bad45b9478fa0356e8427a4e should resolve the issue.

Having that said, there was an issue with StAX and EXI compression on.

Please let me know if the issue is resolved.

**Comment by mkrzempek** [comment]
It seems that problem is resolved. Thanks a lot.
